//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 170.141838 on Stable branch
// Generated with ALiVE version 1.3.5.1705161
//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
    class ALIVE_BANDITS {
        units[] = {
            "O_OPFGFcopy1_Truck_01",
            "O_OPFGFcopy1_Sharpshooter_01",
            "O_OPFGFcopy1_Mk6_Mortar_01",
            "O_OPFGFcopy1_Assault_Boat_01",
            "O_OPFGFcopy1_Offroad_Repair_01",
            "O_OPFGFcopy1_Offroad_01",
            "O_OPFGFcopy1_Offroad_Armed_01",
            "O_OPFGFcopy1_Quad_Bike_01",
            "O_OPFGFcopy1_Fuel_Truck_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Soft_F_Gamma_Van_01",
            "A3_Characters_F",
            "exile_client",
            "A3_Static_F_Mortar_01",
            "cba_xeh",
            "A3_Boat_F_Boat_Transport_01",
            "A3_Boat_F_Exp_Boat_Transport_01",
            "A3_Soft_F_Offroad_01",
            "A3_Soft_F_Quadbike_01"
        };
        author = "coldnebo";
        authors[] = { "coldnebo" };
    };
};

class CfgFactionClasses {
    class ALIVE_BANDITS {
        displayName = "ALIVE Bandits";
        side = 0;
        flag = "\a3\Data_f\Flags\flag_FIA_co.paa";
        icon = "\a3\Data_f\cfgFactionClasses_IND_G_ca.paa";
        priority = 2;
    };
};

class CfgGroups {
    class EAST {

        class ALIVE_BANDITS {
            name = "ALIVE Bandits";

            class Infantry {
                name = "Infantry";

                class ORG_InfSentry {
                    name = "Sentry";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_GL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                };

                class ORG_InfSquad {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_SL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_A_F";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_medic_F";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                };

                class ORG_InfSquad_Weapons {
                    name = "Weapons Squad";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_SL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit5 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                    class Unit6 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_A_F";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_medic_F";
                    };
                };

                class ORG_InfTeam {
                    name = "Fire Team";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_GL_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                };

                class ORG_InfTeam_AA {
                    name = "Air-defense Team";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_A_F";
                    };
                };

                class ORG_InfTeam_AT {
                    name = "Anti-armor Team";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_A_F";
                    };
                };

                class ORG_InfWepTeam {
                    name = "Weapons Team";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 5 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 3 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit2 {
                        position[] = { 5 , 0 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit3 {
                        position[] = { 7 , 0 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                };

                class ORG_InfSupTeam {
                    name = "Support Team";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = { 0 , 5 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 3 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit2 {
                        position[] = { 5 , 0 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_medic_F";
                    };
                    class Unit3 {
                        position[] = { 7 , 0 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_M_F";
                    };
                };

                class ORG_InfHQ {
                    name = "Infantry HQ";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 5 , 0 };
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_G_Soldier_SL_F";
                    };
                    class Unit1 {
                        position[] = { 3 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit2 {
                        position[] = { 5 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_medic_F";
                    };
                    class Unit3 {
                        position[] = { 7 , 0 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_engineer_F";
                    };
                    class Unit4 {
                        position[] = { 9 , 0 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                };

                class ORG_ReconSentry {
                    name = "Recon Sentry";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

                class ORG_MotInf_Team {
                    name = "Motorized Patrol";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 0 , -10 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OPFGFcopy1_Offroad_01";
                    };
                    class Unit2 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit3 {
                        position[] = { -5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_LAT_F";
                    };
                    class Unit4 {
                        position[] = { 10 , -10 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_medic_F";
                    };
                    class Unit5 {
                        position[] = { -10 , -10 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                };

                class ORG_Technicals {
                    name = "Technicals";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OPFGFcopy1_Offroad_Armed_01";
                    };
                    class Unit1 {
                        position[] = { 10 , -10 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OPFGFcopy1_Offroad_Armed_01";
                    };
                    class Unit2 {
                        position[] = { -10 , -10 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OPFGFcopy1_Offroad_Armed_01";
                    };
                };

            };

            class Support {
                name = "Support Infantry";

                class ORG_Support_CLS {
                    name = "Support Team (CLS)";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_AR_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_medic_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_medic_F";
                    };
                };

                class ORG_Support_ENG {
                    name = "Support Team (Engineer)";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_engineer_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_engineer_F";
                    };
                };

                class ORG_Support_EOD {
                    name = "Support Team (EOD)";
                    side = 0;
                    faction = "ALIVE_BANDITS";
                    icon = "";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_G_Soldier_TL_F";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_G_Soldier_F";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_engineer_F";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_G_engineer_F";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_G_Van_01_transport_F;
    class I_G_Van_01_transport_F_OCimport_01 : I_G_Van_01_transport_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Van_01_transport_F_OCimport_02 : I_G_Van_01_transport_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_L1;
            class CargoTurret_L2;
            class CargoTurret_L3;
            class CargoTurret_L4;
            class CargoTurret_L5;
            class CargoTurret_R1;
            class CargoTurret_R2;
            class CargoTurret_R3;
            class CargoTurret_R4;
            class CargoTurret_R5;
        };
    };

    class I_G_Sharpshooter_F;
    class I_G_Sharpshooter_F_OCimport_01 : I_G_Sharpshooter_F { scope = 0; class EventHandlers; };
    class I_G_Sharpshooter_F_OCimport_02 : I_G_Sharpshooter_F_OCimport_01 { class EventHandlers; };

    class I_G_Mortar_01_F;
    class I_G_Mortar_01_F_OCimport_01 : I_G_Mortar_01_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Mortar_01_F_OCimport_02 : I_G_Mortar_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_G_Boat_Transport_01_F;
    class I_G_Boat_Transport_01_F_OCimport_01 : I_G_Boat_Transport_01_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Boat_Transport_01_F_OCimport_02 : I_G_Boat_Transport_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class Offroad_01_repair_military_base_F;
    class Offroad_01_repair_military_base_F_OCimport_01 : Offroad_01_repair_military_base_F { scope = 0; class EventHandlers; };
    class Offroad_01_repair_military_base_F_OCimport_02 : Offroad_01_repair_military_base_F_OCimport_01 { scope = 0; class EventHandlers; };

    class I_G_Offroad_01_F;
    class I_G_Offroad_01_F_OCimport_01 : I_G_Offroad_01_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Offroad_01_F_OCimport_02 : I_G_Offroad_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class I_G_Offroad_01_armed_F;
    class I_G_Offroad_01_armed_F_OCimport_01 : I_G_Offroad_01_armed_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Offroad_01_armed_F_OCimport_02 : I_G_Offroad_01_armed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class M2_Turret;
        };
    };

    class I_G_Quadbike_01_F;
    class I_G_Quadbike_01_F_OCimport_01 : I_G_Quadbike_01_F { scope = 0; class EventHandlers; };
    class I_G_Quadbike_01_F_OCimport_02 : I_G_Quadbike_01_F_OCimport_01 { scope = 0; class EventHandlers; };

    class I_G_Van_01_fuel_F;
    class I_G_Van_01_fuel_F_OCimport_01 : I_G_Van_01_fuel_F { scope = 0; class EventHandlers; };
    class I_G_Van_01_fuel_F_OCimport_02 : I_G_Van_01_fuel_F_OCimport_01 { scope = 0; class EventHandlers; };


    class O_OPFGFcopy1_Truck_01 : I_G_Van_01_transport_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";

        class Turrets : Turrets {
            class CargoTurret_L1 : CargoTurret_L1 { gunnerType = ""; };
            class CargoTurret_L2 : CargoTurret_L2 { gunnerType = ""; };
            class CargoTurret_L3 : CargoTurret_L3 { gunnerType = ""; };
            class CargoTurret_L4 : CargoTurret_L4 { gunnerType = ""; };
            class CargoTurret_L5 : CargoTurret_L5 { gunnerType = ""; };
            class CargoTurret_R1 : CargoTurret_R1 { gunnerType = ""; };
            class CargoTurret_R2 : CargoTurret_R2 { gunnerType = ""; };
            class CargoTurret_R3 : CargoTurret_R3 { gunnerType = ""; };
            class CargoTurret_R4 : CargoTurret_R4 { gunnerType = ""; };
            class CargoTurret_R5 : CargoTurret_R5 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Sharpshooter_01 : I_G_Sharpshooter_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sharpshooter";
        side = 0;
        faction = "ALIVE_BANDITS";

        identityTypes[] = { "Head_Greek" , "LanguageGRE_F" , "G_GUERIL_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['srifle_DMR_06_camo_khs_F','','','optic_KHS_old',['20Rnd_762x51_Mag',20],[],''],[],[],[],['V_BandollierB_oli',[['FirstAidKit',1],['20Rnd_762x51_Mag',6,20]]],[],'H_Booniehat_khk_hs','G_Bandanna_tan',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Mk6_Mortar_01 : I_G_Mortar_01_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mk6 Mortar";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Assault_Boat_01 : I_G_Boat_Transport_01_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assault Boat";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Offroad_Repair_01 : Offroad_01_repair_military_base_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad (Repair)";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Offroad_01 : I_G_Offroad_01_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Offroad_Armed_01 : I_G_Offroad_01_armed_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad (Armed)";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Quad_Bike_01 : I_G_Quadbike_01_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Quad Bike";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OPFGFcopy1_Fuel_Truck_01 : I_G_Van_01_fuel_F_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Fuel Truck";
        side = 0;
        faction = "ALIVE_BANDITS";
        crew = "O_G_Soldier_F";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};