//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 170.141838 on Stable branch
// Generated with ALiVE version 1.3.5.1705161
//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
    class ALIVE_DINOS {
        units[] = {
            "I_Dinoscopy1_Raptor_Female2_AI_01",
            "I_Dinoscopy1_Raptor_Female_01",
            "I_Dinoscopy1_Raptor_Female_2_01",
            "I_Dinoscopy1_Raptor_Male_01",
            "I_Dinoscopy1_Raptor_Female_AI_01",
            "I_Dinoscopy1_Raptor_Male_AI_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "RUP_Dinosaurs",
            "A3_Characters_F",
            "exile_client",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USArmy",
            "CUP_Creatures_Military_USMC",
            "CUP_Creatures_People_Civil_Chernarus",
            "CUP_Creatures_People_Civil_Russia",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta"
        };
        author = "coldnebo";
        authors[] = { "coldnebo" };
    };
};

class CfgFactionClasses {
    class ALIVE_DINOS {
        displayName = "ALIVE Dinosaurs";
        side = 1;
        flag = "";
        icon = "\Rup_Dinosaurs\Data\All\Icon.paa";
        priority = 2;
    };
};

class CfgGroups {
    class WEST {

        class ALIVE_DINOS {
            name = "ALIVE Dinosaurs";

            class Infantry {
                name = "Infantry";

                class alivedinos_infantry_scouts {
                    name = "Scouts";
                    side = 1;
                    faction = "ALIVE_DINOS";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_Dinoscopy1_Raptor_Female_AI_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_Dinoscopy1_Raptor_Female_AI_01";
                    };
                };

                class alivedinos_infantry_pack {
                    name = "Pack";
                    side = 1;
                    faction = "ALIVE_DINOS";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_Dinoscopy1_Raptor_Female2_AI_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_Dinoscopy1_Raptor_Female_AI_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_Dinoscopy1_Raptor_Male_AI_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_Dinoscopy1_Raptor_Male_AI_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class Raptor2;
    class Raptor2_OCimport_01 : Raptor2 { scope = 0; class EventHandlers; };
    class Raptor2_OCimport_02 : Raptor2_OCimport_01 { class EventHandlers; };

    class Raptor;
    class Raptor_OCimport_01 : Raptor { scope = 0; class EventHandlers; };
    class Raptor_OCimport_02 : Raptor_OCimport_01 { class EventHandlers; };


    class I_Dinoscopy1_Raptor_Female2_AI_01 : Raptor2_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raptor Female2 AI";
        side = 1;
        faction = "ALIVE_DINOS";

        identityTypes[] = { "RaptorF2_ID1" , "RaptorF2_ID2" , "RaptorF2_ID3" , "RaptorF2_ID4" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['RaptorAttack','','','',[],[],''],[],[],['Raptor_Uniform_Base',[]],[],[],'','',['NVGoggles','','','',[],[],''],['','','','','','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Dinoscopy1_Raptor_Female_01 : Raptor_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raptor Female";
        side = 1;
        faction = "ALIVE_DINOS";

        identityTypes[] = { "RaptorF1_ID1" , "RaptorF1_ID2" , "RaptorF1_ID3" , "RaptorF1_ID4" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['RaptorAttack','','','',['RaptorAttack_Mag',1e+008],[],''],[],[],['Raptor_Uniform_Base',[]],[],[],'','',[],['','','','','','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Dinoscopy1_Raptor_Female_2_01 : Raptor_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raptor Female 2";
        side = 1;
        faction = "ALIVE_DINOS";

        identityTypes[] = { "RaptorF2_ID1" , "RaptorF2_ID2" , "RaptorF2_ID3" , "RaptorF2_ID4" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['RaptorAttack','','','',['RaptorAttack_Mag',1e+008],[],''],[],[],['Raptor_Uniform_Base',[]],[],[],'','',[],['','','','','','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Dinoscopy1_Raptor_Male_01 : Raptor_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raptor Male";
        side = 1;
        faction = "ALIVE_DINOS";

        identityTypes[] = { "RaptorM1_ID1" , "RaptorM1_ID2" , "RaptorM1_ID3" , "RaptorM1_ID4" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['RaptorAttack','','','',['RaptorAttack_Mag',1e+008],[],''],[],[],['RaptorM_Uniform_Base',[]],[],[],'','',[],['','','','','','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Dinoscopy1_Raptor_Female_AI_01 : Raptor_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raptor Female AI";
        side = 1;
        faction = "ALIVE_DINOS";

        identityTypes[] = { "RaptorF2_ID1" , "RaptorF2_ID2" , "RaptorF2_ID3" , "RaptorF2_ID4" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['RaptorAttack','','','',[],[],''],[],[],['Raptor_Uniform_Base',[]],[],[],'','',['NVGoggles','','','',[],[],''],['','','','','','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Dinoscopy1_Raptor_Male_AI_01 : Raptor2_OCimport_02 {
        author = "coldnebo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raptor Male AI";
        side = 1;
        faction = "ALIVE_DINOS";

        identityTypes[] = { "RaptorM1_ID1" , "RaptorM1_ID2" , "RaptorM1_ID3" , "RaptorM1_ID4" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['RaptorAttack','','','',[],[],''],[],[],['RaptorM_Uniform_Base',[]],[],[],'','',['NVGoggles','','','',[],[],''],['','','','','','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};